### ISSUE TITLE
Go noop in production mode

### ISSUE THREAD

**Issue by langpavel** [joonhocho/proptypes-parser#1]
It's wasting by resources in production unless using something like [react-redux-provide](https://github.com/loggur/react-redux-provide).

Please add a note to `README.md` :-)

**Comment by joonhocho** [comment]
Thanks for feedback.
It now returns a No-op function when `process.env.NODE_ENV === 'production'`.
Take a look at the source.
https://github.com/joonhocho/proptypes-parser/blob/master/src/index.js

**Comment by langpavel** [comment]
Ok, I was looking at your pretty state machine but this condition I missed. Still it will be nice putting a note to README :-) There is at least one library I know about that use `PropTypes` in production, especially for `shouldComponentUpdate` logic.

**Comment by joonhocho** [comment]
Added a note to README regarding production use.
I think babel/webpack plugins will be the best solution for different production use cases.
