### ISSUE TITLE
Babel plugin?

### ISSUE THREAD

**Issue by langpavel** [joonhocho/proptypes-parser#2]
It will be nice if this module can be used as a part of Babel transpilation step.

Like [react-intl](https://github.com/yahoo/react-intl/blob/master/examples/translations/.babelrc) do.

**Comment by joonhocho** [comment]
Yeah, totally!
That is in the TODO section in the Readme.md.
I have never worked on Babel plugins, yet.
Hopefully, someone with experience can help me out on that.

**Comment by langpavel** [comment]
React-intl do this in [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js). I'm not sure if this is helpful link but dropping here because I searched around and wish to note somewhere..

Possible solution:
1. Detect for import or require statement of `proptypes-parser`
2. Then detect call of parser in form of template string or simply function call

**Comment by joonhocho** [comment]
I will take a look when I get freed up.

**Comment by langpavel** [comment]
Yeah, It's challenging :-)

**Comment by joonhocho** [comment]
@langpavel, do you think there is any reason that https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types shouldn't just work?
I've looked at its source and it seems like it should also work for `proptypes-parser`.

**Comment by joonhocho** [comment]
I've added [examples](https://github.com/joonhocho/proptypes-parser/tree/master/examples) and confirmed that the plugin indeed removes propTypes for production.
