### ISSUE TITLE
Remove lib from version control

### ISSUE THREAD

**Issue by langpavel** [joonhocho/proptypes-parser#4]
Hi. I recommend you to remove `lib` directory from git. Diffs will be more readable and conflicts when merging/rebasing much more simpler.

I make once this error and somebody sent me PR with modification only in generated code.. :-D

You should create `.npmignore` file which ensures that lib be present when publishing package

**Comment by joonhocho** [comment]
Do you have an example repo that does this? I am noob to publishing on npm, and not sure how I can have lib/ only on npm and not on git. Doesn't npm pull source from git?

**Comment by rt2zz** [comment]
redux does this. The only downside is it breaks npm install from github master (since the built version is not in git)

To make that play nicely with npm publish you will want to add a prepublish script:
https://github.com/rt2zz/redux-persist/blob/master/package.json#L12 and specify files to include in package.json: https://github.com/rt2zz/redux-persist/blob/master/package.json#L47-L51

**Comment by langpavel** [comment]
My project [node-pg-async](https://github.com/langpavel/node-pg-async) does this. I do not have prepublish script, this is usefull, but I have issues with CI and I remove it.

`npm publish` does not pull from git. From [npm developers page](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):

> Use a `.npmignore` file to keep stuff out of your package. If there's no `.npmignore` file, but there is a `.gitignore` file, then npm will ignore the stuff matched by the `.gitignore` file. If you want to include something that is excluded by your `.gitignore` file, you can create an empty `.npmignore` file to override it. Like git, npm looks for `.npmignore` and `.gitignore` files in all subdirectories of your package, not only the root directory.
> 
> `.npmignore` files follow the same pattern rules as `.gitignore` files:
> - Blank lines or lines starting with # are ignored.
> - Standard glob patterns work.
> - You can end patterns with a forward slash / to specify a directory.
> - You can negate a pattern by starting it with an exclamation point !.
> 
> By default, the following paths and files are ignored, so there's no need to add them to `.npmignore` explicitly:
> - `.*.swp`
> - `._*`
> - `.DS_Store`
> - `.git`
> - `.hg`
> - `.npmrc`
> - `.lock-wscript`
> - `.svn`
> - `.wafpickle-*`
> - `config.gypi`
> - `CVS`
> - `npm-debug.log`
> 
> Additionally, everything in `node_modules` is ignored, except for bundled dependencies. npm automatically handles this for you, so don't bother adding `node_modules` to `.npmignore`.
> 
> The following paths and files are never ignored, so adding them to `.npmignore` is pointless:
> - `package.json`
> - `README (and its variants)`
> - `CHANGELOG (and its variants)`
> - `LICENSE / LICENCE`

**Comment by joonhocho** [comment]
Thanks for help!
I removed lib directory from github and removed src directory from npm.
It's really useful! thanks alot!

**Comment by langpavel** [comment]
You are welcome :-)
